### PR TITLE
Update babel

### PR DESCRIPTION
**Pull request by roopakv**
This resolves an issue when updating to webpack 5: https://github.com/babel/babel/issues/12158

### CODE REVIEW

**Comment by afc163** [comment]
You can upgrade to lastest version of `@babel/runtime`.

**Comment by roopakv** [comment]
@afc163 just deleted my fork :) was going thru my year end clean up routine and it didn't seem like this PR would be reviewed given I opened it over 1.5 years ago 😅 

LMK if you would like me to upgrade babel and I will take another shot at it

**Comment by afc163** [comment]
Happy to review and merge it, sorry for ignoring your PR.

**Comment by afc163** [comment]
https://github.com/react-component/resize-observer/pull/154

**Pull request closed without merging**
